version: '3.3'
services: 
  front-end: 
    image: wsboos/devtool:lastest
    build: ./front-end
    ports:
      - "2560:80"
  back-end:
    image: wsboos/devtool-back:lastest 
    build: ./back-test/app
    ports:
      - "4560:3000"
  
